### ISSUE TITLE
Remove cob_camera_sensors?

### ISSUE THREAD

**Issue by fmessmer** [4am-robotics/cob_driver#115]
@ipa-jsf
@ipa-rmb

Is this package still needed?
Can you please clean this up?

**Comment by floweisshardt** [comment]
there is at least a python script used for setting the camera info for the prosilica cameras: https://github.com/ipa320/cob_driver/tree/hydro_dev/cob_camera_sensors/ros/scripts

I think all other stuff is not used any more because it is not even build by the CMakeList.txt (same for groovy version already)

**Comment by ipa-rmb** [comment]
This is part of Jan's realm. He has to decide.

**Comment by floweisshardt** [comment]
@ipa-jsf: are you still using this stuff? can we delete it?

**Comment by ipa-jsf** [comment]
@ipa-fxm: Keep source and header files: Nedded for windows.
@ipa-fxm: Keep scripts: Needed to convert matlab calibration into yaml format
@ipa-fxm: settings files: to be clarified with ipa-rmb

**Comment by fmessmer** [comment]
obsolete file have been removed in #116
