### ISSUE TITLE
[cob_mimic] the cpp implementation is not working

### ISSUE THREAD

**Issue by NadiaHG** [4am-robotics/cob_driver#355]
the resolution and rotation of the mimic is wrong and can not be configured using the cpp library for vlc

**Comment by NadiaHG** [comment]
could we readd the python node? https://github.com/ipa320/cob_driver/pull/356

**Comment by fmessmer** [comment]
@ipa-nhg 
For which robot has this (resolution and rotation) been wrong?
We tested the cpp-driver with various robots...and we did not experience this problem...

Also, I think we should at least use the python-drver which used the vlc-API...because that way we resolved the flickering problem as described in https://github.com/ipa320/msh/issues/714#issuecomment-302705555....even if this means we have to add the python-vlc module to the mimic package...as was done in https://github.com/ipa320/cob_driver/pull/339 without the last commit https://github.com/ipa320/cob_driver/pull/339/commits/2bf582d05a3c0ac3f3901f0b7f992bada034674f

---
minor:
I also don't like the launch argument ```old``` too much https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/mimic.launch#L5

**Comment by NadiaHG** [comment]
this was for t-labs and probably is the same problem that had paul-ingolstadt.
I had the same issue with the python-driver that uses the vlc-API , this is an issue with the parametrization of vlc. With the APIs we can't set the parameters that we need (specially` --vout glx`), the need of the parameter could also be a problem related to the graphic card driver, paul-stuttgart (where it is working) has a different graphic card model...

Please feel free to modify the argument `old` this was a very urgent hot fix... sorry

**Comment by fmessmer** [comment]
a solution might be provided in https://github.com/ipa320/msh/issues/845#issuecomment-330476261
see https://github.com/ipa320/setup_cob4/pull/152
