### ISSUE TITLE
Cob_trajectory_controller velocity setpoint

### ISSUE THREAD

**Issue by anefg** [4am-robotics/cob_driver#95]
Dear all,

We have a robotnik 6 dof robot arm with Schunk Powercube actuators.
People from Schunk told us that their actuators work with a position control loop. However, we have been analyzing the “cob_trajectory_controller” and it sends velocity setpoints to the schunk_powercube_chain node.
What is the reason to send  velocity setpoints? Is there a conversion from velocity to position in the schunk driver to feed the actuators?

Thanks

**Comment by floweisshardt** [comment]
the conversion from pos to vel is done because the schunk_powercube_chain (libm5API) or the ipa_canopen_ros (CAN Open) are using incremental positions with a predefined time horizon for safety reasons. If the connections gets lost, the modules will only move for the small time horizon and stop but not crash into something.
